## Task 1: Basic Python Programming

##### Write a function `fibonacci(n)` that generates the first `n` numbers in the Fibonacci sequence and returns

In [3]:
def fibonacci(n):
    sequence = []
    a, b = 0, 1
    while len(sequence) < n:
        sequence.append(a)
        a, b = b, a + b
    return sequence

n = int(input("Enter the number: "))
print(fibonacci(n))

Enter the number: 10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

##### Write a function `is_prime(num)` that checks if a given number is a prime number. Return `True` if the number is prime and return 'False' if the number is non-prime

In [4]:
def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

num = int(input("Enter a number: "))
print(is_prime(num))

Enter a number: 3
True

## Task 2: Data Manipulation with Pandas

In [5]:
data = {
'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'],
'Sales': [200, 220, 210, 215, 225],
'Region': ['North', 'South', 'East', 'West', 'North'],
'Manager': ['John', 'Jane', 'Joe', 'Jake', 'John']
}

In [6]:
import pandas as pd
df = pd.DataFrame(data)
df

         Date  Sales Region Manager
0  2024-01-01    200  North    John
1  2024-01-02    220  South    Jane
2  2024-01-03    210   East     Joe
3  2024-01-04    215   West    Jake
4  2024-01-05    225  North    John

##### Load the dataset into a pandas DataFrame and display its first 5 rows.

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

##### Add a new column `Profit` which is 10% of the `Sales` column.

In [8]:
df['Profit'] = df['Sales'] * 0.10
df

         Date  Sales Region Manager  Profit
0  2024-01-01    200  North    John    20.0
1  2024-01-02    220  South    Jane    22.0
2  2024-01-03    210   East     Joe    21.0
3  2024-01-04    215   West    Jake    21.5
4  2024-01-05    225  North    John    22.5

##### Group the data by `Region` and calculate the total sales for each region.

In [9]:
total_sales = df.groupby('Region')['Sales'].sum()
print("\nTotal sales for each region:")
print(total_sales)

Total sales for each region:
Region
East     210
North    425
South    220
West     215
Name: Sales, dtype: int64

##### Find the region with the highest average sales.

In [10]:
average_sales_by_region = df.groupby('Region')['Sales'].mean()
highest_avg_sales = average_sales_by_region.idxmax()
print("\nRegion with the highest average sales:")
print(f"{highest_avg_sales} with an average sales of {average_sales_by_region[highest_avg_sales]:.2f}")

Region with the highest average sales:
South with an average sales of 220.00

## Task 3: Data Loading and Manipulation from GitHub

##### Load a CSV file from a GitHub repository into a pandas DataFrame.

In [15]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df2 = pd.read_csv(url)
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

##### Display summary statistics of the DataFrame.

In [18]:
df2.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

##### Check for null values in the DataFrame and display the count of null values in each column.

In [32]:
df2.isnull().sum()
print("\nMissing values:")
print(df2.isnull().sum())

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
FamilySize       0
dtype: int64

##### Fill the null values in the 'Age' column with the mean age.

In [33]:
df2['Age'].fillna(df2['Age'].mean(), inplace=True)
print("\nMissing values after filling with mean:")
df2['Age'].isnull().sum()

Missing values after filling with mean:

0

##### Drop the rows where 'Embarked' is null.

In [34]:
df2.dropna(subset=['Embarked'], inplace=True)
print("\nMissing values after dropping rows with missing Embarked:")
df['Embarked'].isnull().sum()

Missing values after dropping rows with missing Embarked:

2

##### Create a new column 'FamilySize' which is the sum of 'SibSp' and 'Parch'.

In [24]:
df2['FamilySize'] = df2['SibSp'] + df2['Parch']
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

##### Convert the 'Sex' column to numerical values (male: 0, female: 1).

In [25]:
df2['Sex'] = df2['Sex'].map({'male': 0, 'female': 1})
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0

##### Group the data by 'Pclass' and calculate the average fare for each class.

In [26]:
average_fare_by = df2.groupby('Pclass')['Fare'].mean()
print("\nAverage fare by class:")
print(average_fare_by)

Average fare by class:
Pclass
1    84.193516
2    20.662183
3    13.675550
Name: Fare, dtype: float64

##### Find the most common port of embarkation ('Embarked' column).

In [27]:
most_common_port = df2['Embarked'].mode()[0]
print("\nMost common port of embarkation:")
print(most_common_port)

Most common port of embarkation:
S

##### Create a pivot table that shows the survival rate ('Survived') for each combination of 'Sex' and 'Pclass'.

In [28]:
pivot_table = df2.pivot_table(index='Sex', columns='Pclass', values='Survived', aggfunc='mean')
print("\nPivot table:")
print(pivot_table)

Pivot table:
Pclass         1         2         3
Sex
0       0.368852  0.157407  0.135447
1       0.967391  0.921053  0.500000

In [29]:
pivot_table

Pclass         1         2         3
Sex
0       0.368852  0.157407  0.135447
1       0.967391  0.921053  0.500000